name: tests
on: [push, pull_request]
jobs:
  test:
    name: Tests
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, bcmath, json
          coverage: none

      - name: Composer
        run: composer install --no-progress --no-interaction

      - name: PHPLint
        run: composer run-script lint

      - name: PHPUnit
        run: composer run-script test

      - name: PHPStan
        run: composer run-script static

